# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_ui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(480, 940)
        MainWindow.setMinimumSize(QSize(480, 940))
        MainWindow.setMaximumSize(QSize(480, 940))
        MainWindow.setSizeIncrement(QSize(1, 1))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(9, 9, 461, 921))
        self.tabWidget.setMinimumSize(QSize(0, 0))
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.tab_3_kitsu = QWidget()
        self.tab_3_kitsu.setObjectName(u"tab_3_kitsu")
        self.line_kitsu = QFrame(self.tab_3_kitsu)
        self.line_kitsu.setObjectName(u"line_kitsu")
        self.line_kitsu.setGeometry(QRect(10, 320, 441, 16))
        self.line_kitsu.setMinimumSize(QSize(0, 0))
        self.line_kitsu.setFrameShape(QFrame.HLine)
        self.line_kitsu.setFrameShadow(QFrame.Sunken)
        self.kitsuLayout_2 = QGroupBox(self.tab_3_kitsu)
        self.kitsuLayout_2.setObjectName(u"kitsuLayout_2")
        self.kitsuLayout_2.setGeometry(QRect(10, 10, 441, 61))
        self.kitsuLayout_2.setMinimumSize(QSize(0, 0))
        self.kitsuLayout_2.setMaximumSize(QSize(16777215, 70))
        self.gridLayout_14 = QGridLayout(self.kitsuLayout_2)
        self.gridLayout_14.setObjectName(u"gridLayout_14")
        self.label_user_name = QLabel(self.kitsuLayout_2)
        self.label_user_name.setObjectName(u"label_user_name")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_name.sizePolicy().hasHeightForWidth())
        self.label_user_name.setSizePolicy(sizePolicy)
        self.label_user_name.setMinimumSize(QSize(0, 0))
        self.label_user_name.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.gridLayout_14.addWidget(self.label_user_name, 0, 0, 1, 1)

        self.pushButton_logout = QPushButton(self.kitsuLayout_2)
        self.pushButton_logout.setObjectName(u"pushButton_logout")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton_logout.sizePolicy().hasHeightForWidth())
        self.pushButton_logout.setSizePolicy(sizePolicy1)
        self.pushButton_logout.setMinimumSize(QSize(0, 0))
        self.pushButton_logout.setMaximumSize(QSize(16777215, 70))

        self.gridLayout_14.addWidget(self.pushButton_logout, 0, 2, 1, 1)

        self.commandLinkButton_go_kitsu = QCommandLinkButton(self.kitsuLayout_2)
        self.commandLinkButton_go_kitsu.setObjectName(u"commandLinkButton_go_kitsu")
        self.commandLinkButton_go_kitsu.setMinimumSize(QSize(100, 30))
        self.commandLinkButton_go_kitsu.setMaximumSize(QSize(100, 100))
        self.commandLinkButton_go_kitsu.setSizeIncrement(QSize(0, 0))
        font = QFont()
        font.setFamily(u"Noto Sans CJK KR")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButton_go_kitsu.setFont(font)
        self.commandLinkButton_go_kitsu.setFocusPolicy(Qt.WheelFocus)
        self.commandLinkButton_go_kitsu.setLayoutDirection(Qt.LeftToRight)

        self.gridLayout_14.addWidget(self.commandLinkButton_go_kitsu, 0, 1, 1, 1)

        self.layoutWidget = QWidget(self.tab_3_kitsu)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 80, 441, 231))
        self.kitsuLayout_1 = QGridLayout(self.layoutWidget)
        self.kitsuLayout_1.setObjectName(u"kitsuLayout_1")
        self.kitsuLayout_1.setContentsMargins(0, 0, 0, 0)
        self.label_vid_project = QLabel(self.layoutWidget)
        self.label_vid_project.setObjectName(u"label_vid_project")
        self.label_vid_project.setMinimumSize(QSize(0, 20))
        self.label_vid_project.setMaximumSize(QSize(16777215, 20))
        self.label_vid_project.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.kitsuLayout_1.addWidget(self.label_vid_project, 0, 0, 1, 1)

        self.label_vid_asset = QLabel(self.layoutWidget)
        self.label_vid_asset.setObjectName(u"label_vid_asset")
        self.label_vid_asset.setMinimumSize(QSize(0, 20))
        self.label_vid_asset.setMaximumSize(QSize(16777215, 20))
        self.label_vid_asset.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.kitsuLayout_1.addWidget(self.label_vid_asset, 0, 1, 1, 1)

        self.listWidget_vid_project = QListWidget(self.layoutWidget)
        self.listWidget_vid_project.setObjectName(u"listWidget_vid_project")

        self.kitsuLayout_1.addWidget(self.listWidget_vid_project, 1, 0, 1, 1)

        self.listWidget_vid_asset = QListWidget(self.layoutWidget)
        self.listWidget_vid_asset.setObjectName(u"listWidget_vid_asset")

        self.kitsuLayout_1.addWidget(self.listWidget_vid_asset, 1, 1, 1, 1)

        self.layoutWidget_3 = QWidget(self.tab_3_kitsu)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(10, 370, 441, 171))
        self.hdriLayout_22 = QHBoxLayout(self.layoutWidget_3)
        self.hdriLayout_22.setObjectName(u"hdriLayout_22")
        self.hdriLayout_22.setContentsMargins(0, 0, 0, 0)
        self.listWidget_change_hdri_img = QListWidget(self.layoutWidget_3)
        self.listWidget_change_hdri_img.setObjectName(u"listWidget_change_hdri_img")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.listWidget_change_hdri_img.sizePolicy().hasHeightForWidth())
        self.listWidget_change_hdri_img.setSizePolicy(sizePolicy2)
        self.listWidget_change_hdri_img.setMinimumSize(QSize(140, 0))
        self.listWidget_change_hdri_img.setMaximumSize(QSize(140, 16777215))

        self.hdriLayout_22.addWidget(self.listWidget_change_hdri_img)

        self.hdriLayout_2 = QGroupBox(self.layoutWidget_3)
        self.hdriLayout_2.setObjectName(u"hdriLayout_2")
        sizePolicy.setHeightForWidth(self.hdriLayout_2.sizePolicy().hasHeightForWidth())
        self.hdriLayout_2.setSizePolicy(sizePolicy)
        self.gridLayout_9 = QGridLayout(self.hdriLayout_2)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.label_preview_hdri_img_import = QLabel(self.hdriLayout_2)
        self.label_preview_hdri_img_import.setObjectName(u"label_preview_hdri_img_import")
        sizePolicy.setHeightForWidth(self.label_preview_hdri_img_import.sizePolicy().hasHeightForWidth())
        self.label_preview_hdri_img_import.setSizePolicy(sizePolicy)
        self.label_preview_hdri_img_import.setMinimumSize(QSize(0, 0))
        self.label_preview_hdri_img_import.setScaledContents(True)

        self.gridLayout_9.addWidget(self.label_preview_hdri_img_import, 0, 0, 1, 1)


        self.hdriLayout_22.addWidget(self.hdriLayout_2)

        self.label_change_hdri_img = QLabel(self.tab_3_kitsu)
        self.label_change_hdri_img.setObjectName(u"label_change_hdri_img")
        self.label_change_hdri_img.setGeometry(QRect(10, 340, 411, 21))
        self.label_change_hdri_img.setMinimumSize(QSize(0, 20))
        self.label_change_hdri_img.setMaximumSize(QSize(16777215, 30))
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.label_change_hdri_img.setFont(font1)
        self.label_change_hdri_img.setLayoutDirection(Qt.LeftToRight)
        self.label_change_hdri_img.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.hdriLayout_1 = QGroupBox(self.tab_3_kitsu)
        self.hdriLayout_1.setObjectName(u"hdriLayout_1")
        self.hdriLayout_1.setGeometry(QRect(9, 620, 441, 181))
        self.gridLayout_6 = QGridLayout(self.hdriLayout_1)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.label_preview_hdri_img_add = QLabel(self.hdriLayout_1)
        self.label_preview_hdri_img_add.setObjectName(u"label_preview_hdri_img_add")
        sizePolicy.setHeightForWidth(self.label_preview_hdri_img_add.sizePolicy().hasHeightForWidth())
        self.label_preview_hdri_img_add.setSizePolicy(sizePolicy)
        self.label_preview_hdri_img_add.setMinimumSize(QSize(0, 0))
        self.label_preview_hdri_img_add.setScaledContents(True)

        self.gridLayout_6.addWidget(self.label_preview_hdri_img_add, 0, 0, 1, 1)

        self.layoutWidget_4 = QWidget(self.tab_3_kitsu)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(10, 580, 441, 32))
        self.hdriLayout_4 = QHBoxLayout(self.layoutWidget_4)
        self.hdriLayout_4.setObjectName(u"hdriLayout_4")
        self.hdriLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_hdri_path_2 = QLabel(self.layoutWidget_4)
        self.label_hdri_path_2.setObjectName(u"label_hdri_path_2")
        self.label_hdri_path_2.setMinimumSize(QSize(0, 30))

        self.hdriLayout_4.addWidget(self.label_hdri_path_2)

        self.lineEdit_hdri_path = QLineEdit(self.layoutWidget_4)
        self.lineEdit_hdri_path.setObjectName(u"lineEdit_hdri_path")
        sizePolicy.setHeightForWidth(self.lineEdit_hdri_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_hdri_path.setSizePolicy(sizePolicy)
        self.lineEdit_hdri_path.setMinimumSize(QSize(0, 30))

        self.hdriLayout_4.addWidget(self.lineEdit_hdri_path)

        self.pushButton_hdri_path = QPushButton(self.layoutWidget_4)
        self.pushButton_hdri_path.setObjectName(u"pushButton_hdri_path")
        sizePolicy1.setHeightForWidth(self.pushButton_hdri_path.sizePolicy().hasHeightForWidth())
        self.pushButton_hdri_path.setSizePolicy(sizePolicy1)
        self.pushButton_hdri_path.setMinimumSize(QSize(0, 0))

        self.hdriLayout_4.addWidget(self.pushButton_hdri_path)

        self.label_publish_hdri_img = QLabel(self.tab_3_kitsu)
        self.label_publish_hdri_img.setObjectName(u"label_publish_hdri_img")
        self.label_publish_hdri_img.setGeometry(QRect(10, 550, 411, 20))
        self.label_publish_hdri_img.setMinimumSize(QSize(0, 20))
        self.label_publish_hdri_img.setMaximumSize(QSize(16777215, 20))
        self.label_publish_hdri_img.setFont(font1)
        self.label_publish_hdri_img.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pushButton_publish_hdri_img = QPushButton(self.tab_3_kitsu)
        self.pushButton_publish_hdri_img.setObjectName(u"pushButton_publish_hdri_img")
        self.pushButton_publish_hdri_img.setGeometry(QRect(10, 820, 441, 50))
        self.pushButton_publish_hdri_img.setMinimumSize(QSize(415, 50))
        self.tabWidget.addTab(self.tab_3_kitsu, "")
        self.tab_1_hdri = QWidget()
        self.tab_1_hdri.setObjectName(u"tab_1_hdri")
        self.tab_1_hdri.setEnabled(True)
        self.line_hdri = QFrame(self.tab_1_hdri)
        self.line_hdri.setObjectName(u"line_hdri")
        self.line_hdri.setGeometry(QRect(10, 640, 441, 20))
        self.line_hdri.setMinimumSize(QSize(0, 0))
        self.line_hdri.setFrameShape(QFrame.HLine)
        self.line_hdri.setFrameShadow(QFrame.Sunken)
        self.pushButton_import = QPushButton(self.tab_1_hdri)
        self.pushButton_import.setObjectName(u"pushButton_import")
        self.pushButton_import.setGeometry(QRect(10, 670, 441, 50))
        self.pushButton_import.setMinimumSize(QSize(415, 50))
        self.layoutWidget_5 = QWidget(self.tab_1_hdri)
        self.layoutWidget_5.setObjectName(u"layoutWidget_5")
        self.layoutWidget_5.setGeometry(QRect(10, 390, 441, 246))
        self.renderLayout_5 = QGridLayout(self.layoutWidget_5)
        self.renderLayout_5.setObjectName(u"renderLayout_5")
        self.renderLayout_5.setContentsMargins(0, 0, 0, 0)
        self.lineEdit_sss_sam = QLineEdit(self.layoutWidget_5)
        self.lineEdit_sss_sam.setObjectName(u"lineEdit_sss_sam")
        self.lineEdit_sss_sam.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_sss_sam.sizePolicy().hasHeightForWidth())
        self.lineEdit_sss_sam.setSizePolicy(sizePolicy1)
        self.lineEdit_sss_sam.setMinimumSize(QSize(40, 30))
        self.lineEdit_sss_sam.setMaximumSize(QSize(90, 30))
        self.lineEdit_sss_sam.setSizeIncrement(QSize(100, 25))
        self.lineEdit_sss_sam.setBaseSize(QSize(100, 25))

        self.renderLayout_5.addWidget(self.lineEdit_sss_sam, 6, 1, 1, 1)

        self.label_aov_setting = QLabel(self.layoutWidget_5)
        self.label_aov_setting.setObjectName(u"label_aov_setting")
        sizePolicy1.setHeightForWidth(self.label_aov_setting.sizePolicy().hasHeightForWidth())
        self.label_aov_setting.setSizePolicy(sizePolicy1)
        self.label_aov_setting.setMinimumSize(QSize(0, 20))
        self.label_aov_setting.setMaximumSize(QSize(16777215, 20))
        self.label_aov_setting.setBaseSize(QSize(190, 25))
        self.label_aov_setting.setFont(font1)
        self.label_aov_setting.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.renderLayout_5.addWidget(self.label_aov_setting, 0, 2, 1, 2)

        self.label_diffuse_sam = QLabel(self.layoutWidget_5)
        self.label_diffuse_sam.setObjectName(u"label_diffuse_sam")
        sizePolicy1.setHeightForWidth(self.label_diffuse_sam.sizePolicy().hasHeightForWidth())
        self.label_diffuse_sam.setSizePolicy(sizePolicy1)
        self.label_diffuse_sam.setMinimumSize(QSize(0, 30))
        self.label_diffuse_sam.setMaximumSize(QSize(100, 30))
        self.label_diffuse_sam.setSizeIncrement(QSize(100, 25))
        self.label_diffuse_sam.setBaseSize(QSize(100, 25))
        font2 = QFont()
        font2.setPointSize(10)
        self.label_diffuse_sam.setFont(font2)

        self.renderLayout_5.addWidget(self.label_diffuse_sam, 3, 0, 1, 1)

        self.label_availaov = QLabel(self.layoutWidget_5)
        self.label_availaov.setObjectName(u"label_availaov")
        sizePolicy1.setHeightForWidth(self.label_availaov.sizePolicy().hasHeightForWidth())
        self.label_availaov.setSizePolicy(sizePolicy1)
        self.label_availaov.setMinimumSize(QSize(0, 20))
        self.label_availaov.setMaximumSize(QSize(16777215, 20))
        self.label_availaov.setBaseSize(QSize(190, 25))
        self.label_availaov.setFont(font1)
        self.label_availaov.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.renderLayout_5.addWidget(self.label_availaov, 1, 2, 1, 1)

        self.label_sample_setting = QLabel(self.layoutWidget_5)
        self.label_sample_setting.setObjectName(u"label_sample_setting")
        sizePolicy1.setHeightForWidth(self.label_sample_setting.sizePolicy().hasHeightForWidth())
        self.label_sample_setting.setSizePolicy(sizePolicy1)
        self.label_sample_setting.setMinimumSize(QSize(0, 20))
        self.label_sample_setting.setMaximumSize(QSize(16777215, 20))
        self.label_sample_setting.setBaseSize(QSize(190, 25))
        self.label_sample_setting.setFont(font1)
        self.label_sample_setting.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.renderLayout_5.addWidget(self.label_sample_setting, 0, 0, 1, 2)

        self.lineEdit_specular_sam = QLineEdit(self.layoutWidget_5)
        self.lineEdit_specular_sam.setObjectName(u"lineEdit_specular_sam")
        self.lineEdit_specular_sam.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_specular_sam.sizePolicy().hasHeightForWidth())
        self.lineEdit_specular_sam.setSizePolicy(sizePolicy1)
        self.lineEdit_specular_sam.setMinimumSize(QSize(40, 30))
        self.lineEdit_specular_sam.setMaximumSize(QSize(90, 30))
        self.lineEdit_specular_sam.setSizeIncrement(QSize(100, 25))
        self.lineEdit_specular_sam.setBaseSize(QSize(100, 25))

        self.renderLayout_5.addWidget(self.lineEdit_specular_sam, 4, 1, 1, 1)

        self.lineEdit_trans_sam = QLineEdit(self.layoutWidget_5)
        self.lineEdit_trans_sam.setObjectName(u"lineEdit_trans_sam")
        self.lineEdit_trans_sam.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_trans_sam.sizePolicy().hasHeightForWidth())
        self.lineEdit_trans_sam.setSizePolicy(sizePolicy1)
        self.lineEdit_trans_sam.setMinimumSize(QSize(40, 30))
        self.lineEdit_trans_sam.setMaximumSize(QSize(90, 30))
        self.lineEdit_trans_sam.setSizeIncrement(QSize(100, 25))
        self.lineEdit_trans_sam.setBaseSize(QSize(100, 25))

        self.renderLayout_5.addWidget(self.lineEdit_trans_sam, 5, 1, 1, 1)

        self.label_sss_sam = QLabel(self.layoutWidget_5)
        self.label_sss_sam.setObjectName(u"label_sss_sam")
        sizePolicy1.setHeightForWidth(self.label_sss_sam.sizePolicy().hasHeightForWidth())
        self.label_sss_sam.setSizePolicy(sizePolicy1)
        self.label_sss_sam.setMinimumSize(QSize(0, 30))
        self.label_sss_sam.setMaximumSize(QSize(100, 30))
        self.label_sss_sam.setSizeIncrement(QSize(100, 25))
        self.label_sss_sam.setBaseSize(QSize(100, 25))
        self.label_sss_sam.setFont(font2)

        self.renderLayout_5.addWidget(self.label_sss_sam, 6, 0, 1, 1)

        self.lineEdit_diffuse_sam = QLineEdit(self.layoutWidget_5)
        self.lineEdit_diffuse_sam.setObjectName(u"lineEdit_diffuse_sam")
        self.lineEdit_diffuse_sam.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_diffuse_sam.sizePolicy().hasHeightForWidth())
        self.lineEdit_diffuse_sam.setSizePolicy(sizePolicy1)
        self.lineEdit_diffuse_sam.setMinimumSize(QSize(40, 30))
        self.lineEdit_diffuse_sam.setMaximumSize(QSize(90, 30))
        self.lineEdit_diffuse_sam.setSizeIncrement(QSize(100, 25))
        self.lineEdit_diffuse_sam.setBaseSize(QSize(100, 25))

        self.renderLayout_5.addWidget(self.lineEdit_diffuse_sam, 3, 1, 1, 1)

        self.label_activaov = QLabel(self.layoutWidget_5)
        self.label_activaov.setObjectName(u"label_activaov")
        sizePolicy1.setHeightForWidth(self.label_activaov.sizePolicy().hasHeightForWidth())
        self.label_activaov.setSizePolicy(sizePolicy1)
        self.label_activaov.setMinimumSize(QSize(0, 20))
        self.label_activaov.setMaximumSize(QSize(16777215, 20))
        self.label_activaov.setBaseSize(QSize(190, 25))
        self.label_activaov.setFont(font1)
        self.label_activaov.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.renderLayout_5.addWidget(self.label_activaov, 1, 3, 1, 1)

        self.lineEdit_aa_sam = QLineEdit(self.layoutWidget_5)
        self.lineEdit_aa_sam.setObjectName(u"lineEdit_aa_sam")
        self.lineEdit_aa_sam.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_aa_sam.sizePolicy().hasHeightForWidth())
        self.lineEdit_aa_sam.setSizePolicy(sizePolicy1)
        self.lineEdit_aa_sam.setMinimumSize(QSize(40, 30))
        self.lineEdit_aa_sam.setMaximumSize(QSize(90, 30))
        self.lineEdit_aa_sam.setSizeIncrement(QSize(100, 25))
        self.lineEdit_aa_sam.setBaseSize(QSize(100, 25))

        self.renderLayout_5.addWidget(self.lineEdit_aa_sam, 1, 1, 2, 1)

        self.listWidget_availaov = QListWidget(self.layoutWidget_5)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        QListWidgetItem(self.listWidget_availaov)
        self.listWidget_availaov.setObjectName(u"listWidget_availaov")
        self.listWidget_availaov.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.listWidget_availaov.sizePolicy().hasHeightForWidth())
        self.listWidget_availaov.setSizePolicy(sizePolicy1)

        self.renderLayout_5.addWidget(self.listWidget_availaov, 2, 2, 6, 1)

        self.lineEdit_volume_sam = QLineEdit(self.layoutWidget_5)
        self.lineEdit_volume_sam.setObjectName(u"lineEdit_volume_sam")
        self.lineEdit_volume_sam.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_volume_sam.sizePolicy().hasHeightForWidth())
        self.lineEdit_volume_sam.setSizePolicy(sizePolicy1)
        self.lineEdit_volume_sam.setMinimumSize(QSize(40, 30))
        self.lineEdit_volume_sam.setMaximumSize(QSize(90, 30))
        self.lineEdit_volume_sam.setSizeIncrement(QSize(100, 25))
        self.lineEdit_volume_sam.setBaseSize(QSize(100, 25))

        self.renderLayout_5.addWidget(self.lineEdit_volume_sam, 7, 1, 1, 1)

        self.label_aa_sam = QLabel(self.layoutWidget_5)
        self.label_aa_sam.setObjectName(u"label_aa_sam")
        sizePolicy1.setHeightForWidth(self.label_aa_sam.sizePolicy().hasHeightForWidth())
        self.label_aa_sam.setSizePolicy(sizePolicy1)
        self.label_aa_sam.setMinimumSize(QSize(0, 30))
        self.label_aa_sam.setMaximumSize(QSize(100, 30))
        self.label_aa_sam.setSizeIncrement(QSize(100, 25))
        self.label_aa_sam.setBaseSize(QSize(100, 25))
        self.label_aa_sam.setFont(font2)

        self.renderLayout_5.addWidget(self.label_aa_sam, 1, 0, 2, 1)

        self.listWidget_activaov = QListWidget(self.layoutWidget_5)
        self.listWidget_activaov.setObjectName(u"listWidget_activaov")
        self.listWidget_activaov.setEnabled(False)

        self.renderLayout_5.addWidget(self.listWidget_activaov, 2, 3, 6, 1)

        self.label_specular_sam = QLabel(self.layoutWidget_5)
        self.label_specular_sam.setObjectName(u"label_specular_sam")
        sizePolicy1.setHeightForWidth(self.label_specular_sam.sizePolicy().hasHeightForWidth())
        self.label_specular_sam.setSizePolicy(sizePolicy1)
        self.label_specular_sam.setMinimumSize(QSize(0, 30))
        self.label_specular_sam.setMaximumSize(QSize(100, 30))
        self.label_specular_sam.setSizeIncrement(QSize(100, 25))
        self.label_specular_sam.setBaseSize(QSize(100, 25))
        self.label_specular_sam.setFont(font2)

        self.renderLayout_5.addWidget(self.label_specular_sam, 4, 0, 1, 1)

        self.label_volume_sam = QLabel(self.layoutWidget_5)
        self.label_volume_sam.setObjectName(u"label_volume_sam")
        self.label_volume_sam.setEnabled(True)
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_volume_sam.sizePolicy().hasHeightForWidth())
        self.label_volume_sam.setSizePolicy(sizePolicy3)
        self.label_volume_sam.setMinimumSize(QSize(0, 30))
        self.label_volume_sam.setMaximumSize(QSize(100, 30))
        self.label_volume_sam.setSizeIncrement(QSize(100, 25))
        self.label_volume_sam.setBaseSize(QSize(100, 25))
        self.label_volume_sam.setFont(font2)

        self.renderLayout_5.addWidget(self.label_volume_sam, 7, 0, 1, 1)

        self.label_trans_sam = QLabel(self.layoutWidget_5)
        self.label_trans_sam.setObjectName(u"label_trans_sam")
        sizePolicy1.setHeightForWidth(self.label_trans_sam.sizePolicy().hasHeightForWidth())
        self.label_trans_sam.setSizePolicy(sizePolicy1)
        self.label_trans_sam.setMinimumSize(QSize(0, 30))
        self.label_trans_sam.setMaximumSize(QSize(100, 30))
        self.label_trans_sam.setSizeIncrement(QSize(100, 25))
        self.label_trans_sam.setBaseSize(QSize(100, 25))
        self.label_trans_sam.setFont(font2)

        self.renderLayout_5.addWidget(self.label_trans_sam, 5, 0, 1, 1)

        self.layoutWidget_6 = QWidget(self.tab_1_hdri)
        self.layoutWidget_6.setObjectName(u"layoutWidget_6")
        self.layoutWidget_6.setGeometry(QRect(10, 110, 441, 270))
        self.renderLayout_4 = QGridLayout(self.layoutWidget_6)
        self.renderLayout_4.setObjectName(u"renderLayout_4")
        self.renderLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_vid_name = QLabel(self.layoutWidget_6)
        self.label_vid_name.setObjectName(u"label_vid_name")
        sizePolicy1.setHeightForWidth(self.label_vid_name.sizePolicy().hasHeightForWidth())
        self.label_vid_name.setSizePolicy(sizePolicy1)
        self.label_vid_name.setMinimumSize(QSize(0, 30))
        self.label_vid_name.setMaximumSize(QSize(100, 16777215))
        self.label_vid_name.setSizeIncrement(QSize(100, 25))
        self.label_vid_name.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.label_vid_name, 5, 2, 1, 1)

        self.label_img_format = QLabel(self.layoutWidget_6)
        self.label_img_format.setObjectName(u"label_img_format")
        sizePolicy1.setHeightForWidth(self.label_img_format.sizePolicy().hasHeightForWidth())
        self.label_img_format.setSizePolicy(sizePolicy1)
        self.label_img_format.setMinimumSize(QSize(0, 30))
        self.label_img_format.setMaximumSize(QSize(100, 16777215))
        self.label_img_format.setSizeIncrement(QSize(100, 25))
        self.label_img_format.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.label_img_format, 3, 2, 1, 1)

        self.label_mesh_start_frame = QLabel(self.layoutWidget_6)
        self.label_mesh_start_frame.setObjectName(u"label_mesh_start_frame")
        sizePolicy1.setHeightForWidth(self.label_mesh_start_frame.sizePolicy().hasHeightForWidth())
        self.label_mesh_start_frame.setSizePolicy(sizePolicy1)
        self.label_mesh_start_frame.setMinimumSize(QSize(0, 30))
        self.label_mesh_start_frame.setMaximumSize(QSize(90, 16777215))
        self.label_mesh_start_frame.setBaseSize(QSize(90, 25))

        self.renderLayout_4.addWidget(self.label_mesh_start_frame, 2, 0, 1, 1)

        self.label_vid_path = QLabel(self.layoutWidget_6)
        self.label_vid_path.setObjectName(u"label_vid_path")
        sizePolicy1.setHeightForWidth(self.label_vid_path.sizePolicy().hasHeightForWidth())
        self.label_vid_path.setSizePolicy(sizePolicy1)
        self.label_vid_path.setMinimumSize(QSize(0, 30))
        self.label_vid_path.setMaximumSize(QSize(100, 16777215))
        self.label_vid_path.setSizeIncrement(QSize(100, 25))
        self.label_vid_path.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.label_vid_path, 7, 2, 1, 1)

        self.label_mesh_end_frame = QLabel(self.layoutWidget_6)
        self.label_mesh_end_frame.setObjectName(u"label_mesh_end_frame")
        sizePolicy1.setHeightForWidth(self.label_mesh_end_frame.sizePolicy().hasHeightForWidth())
        self.label_mesh_end_frame.setSizePolicy(sizePolicy1)
        self.label_mesh_end_frame.setMinimumSize(QSize(0, 30))
        self.label_mesh_end_frame.setMaximumSize(QSize(90, 16777215))
        self.label_mesh_end_frame.setBaseSize(QSize(90, 25))

        self.renderLayout_4.addWidget(self.label_mesh_end_frame, 3, 0, 1, 1)

        self.checkBox_change_setting = QCheckBox(self.layoutWidget_6)
        self.checkBox_change_setting.setObjectName(u"checkBox_change_setting")
        self.checkBox_change_setting.setEnabled(True)
        self.checkBox_change_setting.setMaximumSize(QSize(16777215, 16777215))

        self.renderLayout_4.addWidget(self.checkBox_change_setting, 0, 0, 1, 2)

        self.label_img_path = QLabel(self.layoutWidget_6)
        self.label_img_path.setObjectName(u"label_img_path")
        sizePolicy1.setHeightForWidth(self.label_img_path.sizePolicy().hasHeightForWidth())
        self.label_img_path.setSizePolicy(sizePolicy1)
        self.label_img_path.setMinimumSize(QSize(0, 30))
        self.label_img_path.setMaximumSize(QSize(100, 16777215))
        self.label_img_path.setSizeIncrement(QSize(100, 25))
        self.label_img_path.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.label_img_path, 4, 2, 1, 1)

        self.lineEdit_mesh_start_frame = QLineEdit(self.layoutWidget_6)
        self.lineEdit_mesh_start_frame.setObjectName(u"lineEdit_mesh_start_frame")
        self.lineEdit_mesh_start_frame.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_mesh_start_frame.sizePolicy().hasHeightForWidth())
        self.lineEdit_mesh_start_frame.setSizePolicy(sizePolicy1)
        self.lineEdit_mesh_start_frame.setMinimumSize(QSize(0, 30))
        self.lineEdit_mesh_start_frame.setMaximumSize(QSize(40, 16777215))
        self.lineEdit_mesh_start_frame.setBaseSize(QSize(60, 25))

        self.renderLayout_4.addWidget(self.lineEdit_mesh_start_frame, 2, 1, 1, 1)

        self.lineEdit_mesh_end_frame = QLineEdit(self.layoutWidget_6)
        self.lineEdit_mesh_end_frame.setObjectName(u"lineEdit_mesh_end_frame")
        self.lineEdit_mesh_end_frame.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_mesh_end_frame.sizePolicy().hasHeightForWidth())
        self.lineEdit_mesh_end_frame.setSizePolicy(sizePolicy1)
        self.lineEdit_mesh_end_frame.setMinimumSize(QSize(0, 30))
        self.lineEdit_mesh_end_frame.setMaximumSize(QSize(40, 16777215))
        self.lineEdit_mesh_end_frame.setBaseSize(QSize(60, 25))

        self.renderLayout_4.addWidget(self.lineEdit_mesh_end_frame, 3, 1, 1, 1)

        self.lineEdit_vid_format = QLineEdit(self.layoutWidget_6)
        self.lineEdit_vid_format.setObjectName(u"lineEdit_vid_format")
        self.lineEdit_vid_format.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_vid_format.sizePolicy().hasHeightForWidth())
        self.lineEdit_vid_format.setSizePolicy(sizePolicy1)
        self.lineEdit_vid_format.setMinimumSize(QSize(0, 30))
        self.lineEdit_vid_format.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_vid_format.setSizeIncrement(QSize(100, 25))
        self.lineEdit_vid_format.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.lineEdit_vid_format, 6, 3, 1, 1)

        self.label_video_setting = QLabel(self.layoutWidget_6)
        self.label_video_setting.setObjectName(u"label_video_setting")
        sizePolicy1.setHeightForWidth(self.label_video_setting.sizePolicy().hasHeightForWidth())
        self.label_video_setting.setSizePolicy(sizePolicy1)
        self.label_video_setting.setMinimumSize(QSize(0, 20))
        self.label_video_setting.setMaximumSize(QSize(16777215, 16777215))
        self.label_video_setting.setBaseSize(QSize(190, 25))
        self.label_video_setting.setFont(font1)
        self.label_video_setting.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.renderLayout_4.addWidget(self.label_video_setting, 1, 2, 1, 2)

        self.label_vid_format = QLabel(self.layoutWidget_6)
        self.label_vid_format.setObjectName(u"label_vid_format")
        sizePolicy1.setHeightForWidth(self.label_vid_format.sizePolicy().hasHeightForWidth())
        self.label_vid_format.setSizePolicy(sizePolicy1)
        self.label_vid_format.setMinimumSize(QSize(0, 30))
        self.label_vid_format.setMaximumSize(QSize(100, 16777215))
        self.label_vid_format.setSizeIncrement(QSize(100, 25))
        self.label_vid_format.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.label_vid_format, 6, 2, 1, 1)

        self.lineEdit_vid_path = QLineEdit(self.layoutWidget_6)
        self.lineEdit_vid_path.setObjectName(u"lineEdit_vid_path")
        self.lineEdit_vid_path.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_vid_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_vid_path.setSizePolicy(sizePolicy1)
        self.lineEdit_vid_path.setMinimumSize(QSize(0, 30))
        self.lineEdit_vid_path.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_vid_path.setSizeIncrement(QSize(100, 25))
        self.lineEdit_vid_path.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.lineEdit_vid_path, 7, 3, 1, 1)

        self.label_img_name = QLabel(self.layoutWidget_6)
        self.label_img_name.setObjectName(u"label_img_name")
        sizePolicy1.setHeightForWidth(self.label_img_name.sizePolicy().hasHeightForWidth())
        self.label_img_name.setSizePolicy(sizePolicy1)
        self.label_img_name.setMinimumSize(QSize(0, 30))
        self.label_img_name.setMaximumSize(QSize(100, 16777215))
        self.label_img_name.setSizeIncrement(QSize(100, 25))
        self.label_img_name.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.label_img_name, 2, 2, 1, 1)

        self.lineEdit_vid_name = QLineEdit(self.layoutWidget_6)
        self.lineEdit_vid_name.setObjectName(u"lineEdit_vid_name")
        self.lineEdit_vid_name.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_vid_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_vid_name.setSizePolicy(sizePolicy1)
        self.lineEdit_vid_name.setMinimumSize(QSize(0, 30))
        self.lineEdit_vid_name.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_vid_name.setSizeIncrement(QSize(100, 25))
        self.lineEdit_vid_name.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.lineEdit_vid_name, 5, 3, 1, 1)

        self.lineEdit_img_path = QLineEdit(self.layoutWidget_6)
        self.lineEdit_img_path.setObjectName(u"lineEdit_img_path")
        self.lineEdit_img_path.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_img_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_img_path.setSizePolicy(sizePolicy1)
        self.lineEdit_img_path.setMinimumSize(QSize(0, 30))
        self.lineEdit_img_path.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_img_path.setSizeIncrement(QSize(100, 25))
        self.lineEdit_img_path.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.lineEdit_img_path, 4, 3, 1, 1)

        self.lineEdit_img_format = QLineEdit(self.layoutWidget_6)
        self.lineEdit_img_format.setObjectName(u"lineEdit_img_format")
        self.lineEdit_img_format.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_img_format.sizePolicy().hasHeightForWidth())
        self.lineEdit_img_format.setSizePolicy(sizePolicy1)
        self.lineEdit_img_format.setMinimumSize(QSize(0, 30))
        self.lineEdit_img_format.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_img_format.setSizeIncrement(QSize(100, 25))
        self.lineEdit_img_format.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.lineEdit_img_format, 3, 3, 1, 1)

        self.lineEdit_img_name = QLineEdit(self.layoutWidget_6)
        self.lineEdit_img_name.setObjectName(u"lineEdit_img_name")
        self.lineEdit_img_name.setEnabled(False)
        sizePolicy1.setHeightForWidth(self.lineEdit_img_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_img_name.setSizePolicy(sizePolicy1)
        self.lineEdit_img_name.setMinimumSize(QSize(0, 30))
        self.lineEdit_img_name.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_img_name.setSizeIncrement(QSize(100, 25))
        self.lineEdit_img_name.setBaseSize(QSize(100, 25))

        self.renderLayout_4.addWidget(self.lineEdit_img_name, 2, 3, 1, 1)

        self.label_mesh = QLabel(self.layoutWidget_6)
        self.label_mesh.setObjectName(u"label_mesh")
        sizePolicy1.setHeightForWidth(self.label_mesh.sizePolicy().hasHeightForWidth())
        self.label_mesh.setSizePolicy(sizePolicy1)
        self.label_mesh.setMinimumSize(QSize(0, 20))
        self.label_mesh.setMaximumSize(QSize(16777215, 16777215))
        self.label_mesh.setBaseSize(QSize(150, 25))
        self.label_mesh.setFont(font1)
        self.label_mesh.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.renderLayout_4.addWidget(self.label_mesh, 1, 0, 1, 2)

        self.renderLayout_1 = QGroupBox(self.tab_1_hdri)
        self.renderLayout_1.setObjectName(u"renderLayout_1")
        self.renderLayout_1.setGeometry(QRect(10, 10, 441, 70))
        sizePolicy.setHeightForWidth(self.renderLayout_1.sizePolicy().hasHeightForWidth())
        self.renderLayout_1.setSizePolicy(sizePolicy)
        self.renderLayout_1.setMinimumSize(QSize(0, 70))
        self.renderLayout_1.setMaximumSize(QSize(16777215, 70))
        self.gridLayout_5 = QGridLayout(self.renderLayout_1)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.renderLayout_2 = QGridLayout()
        self.renderLayout_2.setObjectName(u"renderLayout_2")
        self.label_name = QLabel(self.renderLayout_1)
        self.label_name.setObjectName(u"label_name")
        sizePolicy1.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy1)
        self.label_name.setMinimumSize(QSize(0, 0))
        self.label_name.setBaseSize(QSize(50, 20))

        self.renderLayout_2.addWidget(self.label_name, 0, 0, 1, 1)

        self.label_selected_mesh_name = QLabel(self.renderLayout_1)
        self.label_selected_mesh_name.setObjectName(u"label_selected_mesh_name")
        sizePolicy.setHeightForWidth(self.label_selected_mesh_name.sizePolicy().hasHeightForWidth())
        self.label_selected_mesh_name.setSizePolicy(sizePolicy)
        self.label_selected_mesh_name.setMinimumSize(QSize(0, 0))
        self.label_selected_mesh_name.setBaseSize(QSize(150, 20))

        self.renderLayout_2.addWidget(self.label_selected_mesh_name, 0, 1, 1, 1)

        self.label_camera = QLabel(self.renderLayout_1)
        self.label_camera.setObjectName(u"label_camera")
        sizePolicy1.setHeightForWidth(self.label_camera.sizePolicy().hasHeightForWidth())
        self.label_camera.setSizePolicy(sizePolicy1)
        self.label_camera.setMinimumSize(QSize(0, 0))
        self.label_camera.setBaseSize(QSize(50, 20))

        self.renderLayout_2.addWidget(self.label_camera, 1, 0, 1, 1)

        self.label_selected_camera_name = QLabel(self.renderLayout_1)
        self.label_selected_camera_name.setObjectName(u"label_selected_camera_name")
        sizePolicy.setHeightForWidth(self.label_selected_camera_name.sizePolicy().hasHeightForWidth())
        self.label_selected_camera_name.setSizePolicy(sizePolicy)
        self.label_selected_camera_name.setMinimumSize(QSize(0, 0))
        self.label_selected_camera_name.setBaseSize(QSize(150, 20))

        self.renderLayout_2.addWidget(self.label_selected_camera_name, 1, 1, 1, 1)


        self.gridLayout_5.addLayout(self.renderLayout_2, 0, 0, 1, 1)

        self.line_hdri_2 = QFrame(self.tab_1_hdri)
        self.line_hdri_2.setObjectName(u"line_hdri_2")
        self.line_hdri_2.setGeometry(QRect(10, 80, 441, 20))
        self.line_hdri_2.setMinimumSize(QSize(0, 0))
        self.line_hdri_2.setFrameShape(QFrame.HLine)
        self.line_hdri_2.setFrameShadow(QFrame.Sunken)
        self.tabWidget.addTab(self.tab_1_hdri, "")
        self.tab_2_render = QWidget()
        self.tab_2_render.setObjectName(u"tab_2_render")
        self.renderLayout_3 = QGroupBox(self.tab_2_render)
        self.renderLayout_3.setObjectName(u"renderLayout_3")
        self.renderLayout_3.setGeometry(QRect(10, 10, 441, 191))
        sizePolicy3.setHeightForWidth(self.renderLayout_3.sizePolicy().hasHeightForWidth())
        self.renderLayout_3.setSizePolicy(sizePolicy3)
        self.gridLayout_3 = QGridLayout(self.renderLayout_3)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.renderLayout_7 = QGridLayout()
        self.renderLayout_7.setObjectName(u"renderLayout_7")
        self.label_scene_name = QLabel(self.renderLayout_3)
        self.label_scene_name.setObjectName(u"label_scene_name")
        sizePolicy1.setHeightForWidth(self.label_scene_name.sizePolicy().hasHeightForWidth())
        self.label_scene_name.setSizePolicy(sizePolicy1)
        self.label_scene_name.setMinimumSize(QSize(90, 30))
        self.label_scene_name.setMaximumSize(QSize(16777215, 30))
        self.label_scene_name.setBaseSize(QSize(50, 20))

        self.renderLayout_7.addWidget(self.label_scene_name, 1, 0, 1, 1)

        self.lineEdit_scene_name = QLineEdit(self.renderLayout_3)
        self.lineEdit_scene_name.setObjectName(u"lineEdit_scene_name")
        sizePolicy4 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.lineEdit_scene_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_scene_name.setSizePolicy(sizePolicy4)
        self.lineEdit_scene_name.setMinimumSize(QSize(0, 30))
        self.lineEdit_scene_name.setMaximumSize(QSize(16777215, 30))
        self.lineEdit_scene_name.setBaseSize(QSize(220, 20))

        self.renderLayout_7.addWidget(self.lineEdit_scene_name, 1, 1, 1, 1)

        self.comboBox_scene_format = QComboBox(self.renderLayout_3)
        self.comboBox_scene_format.addItem("")
        self.comboBox_scene_format.addItem("")
        self.comboBox_scene_format.setObjectName(u"comboBox_scene_format")
        sizePolicy1.setHeightForWidth(self.comboBox_scene_format.sizePolicy().hasHeightForWidth())
        self.comboBox_scene_format.setSizePolicy(sizePolicy1)
        self.comboBox_scene_format.setMinimumSize(QSize(0, 30))
        self.comboBox_scene_format.setMaximumSize(QSize(16777215, 30))
        self.comboBox_scene_format.setBaseSize(QSize(90, 20))

        self.renderLayout_7.addWidget(self.comboBox_scene_format, 1, 2, 1, 1)

        self.label_scene_path = QLabel(self.renderLayout_3)
        self.label_scene_path.setObjectName(u"label_scene_path")
        sizePolicy1.setHeightForWidth(self.label_scene_path.sizePolicy().hasHeightForWidth())
        self.label_scene_path.setSizePolicy(sizePolicy1)
        self.label_scene_path.setMinimumSize(QSize(90, 30))
        self.label_scene_path.setMaximumSize(QSize(16777215, 30))
        self.label_scene_path.setBaseSize(QSize(50, 20))

        self.renderLayout_7.addWidget(self.label_scene_path, 2, 0, 1, 1)

        self.lineEdit_scene_path = QLineEdit(self.renderLayout_3)
        self.lineEdit_scene_path.setObjectName(u"lineEdit_scene_path")
        sizePolicy4.setHeightForWidth(self.lineEdit_scene_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_scene_path.setSizePolicy(sizePolicy4)
        self.lineEdit_scene_path.setMinimumSize(QSize(0, 30))
        self.lineEdit_scene_path.setMaximumSize(QSize(16777215, 30))
        self.lineEdit_scene_path.setBaseSize(QSize(220, 20))

        self.renderLayout_7.addWidget(self.lineEdit_scene_path, 2, 1, 1, 1)

        self.pushButton_scene_path = QPushButton(self.renderLayout_3)
        self.pushButton_scene_path.setObjectName(u"pushButton_scene_path")
        sizePolicy1.setHeightForWidth(self.pushButton_scene_path.sizePolicy().hasHeightForWidth())
        self.pushButton_scene_path.setSizePolicy(sizePolicy1)
        self.pushButton_scene_path.setMinimumSize(QSize(0, 30))
        self.pushButton_scene_path.setMaximumSize(QSize(16777215, 30))
        self.pushButton_scene_path.setBaseSize(QSize(90, 20))

        self.renderLayout_7.addWidget(self.pushButton_scene_path, 2, 2, 1, 1)

        self.label_save_scene_file = QLabel(self.renderLayout_3)
        self.label_save_scene_file.setObjectName(u"label_save_scene_file")
        self.label_save_scene_file.setMinimumSize(QSize(0, 20))
        self.label_save_scene_file.setMaximumSize(QSize(16777215, 20))
        self.label_save_scene_file.setBaseSize(QSize(150, 20))
        self.label_save_scene_file.setFont(font1)

        self.renderLayout_7.addWidget(self.label_save_scene_file, 0, 0, 1, 3)


        self.gridLayout_3.addLayout(self.renderLayout_7, 1, 0, 1, 1)

        self.pushButton_save_scene = QPushButton(self.renderLayout_3)
        self.pushButton_save_scene.setObjectName(u"pushButton_save_scene")
        sizePolicy1.setHeightForWidth(self.pushButton_save_scene.sizePolicy().hasHeightForWidth())
        self.pushButton_save_scene.setSizePolicy(sizePolicy1)
        self.pushButton_save_scene.setMinimumSize(QSize(0, 50))
        self.pushButton_save_scene.setMaximumSize(QSize(16777215, 50))

        self.gridLayout_3.addWidget(self.pushButton_save_scene, 2, 0, 1, 1)

        self.line_render = QFrame(self.renderLayout_3)
        self.line_render.setObjectName(u"line_render")
        self.line_render.setMinimumSize(QSize(0, 0))
        self.line_render.setFrameShape(QFrame.HLine)
        self.line_render.setFrameShadow(QFrame.Sunken)

        self.gridLayout_3.addWidget(self.line_render, 0, 0, 1, 1)

        self.line_render_1 = QFrame(self.tab_2_render)
        self.line_render_1.setObjectName(u"line_render_1")
        self.line_render_1.setGeometry(QRect(10, 210, 441, 16))
        self.line_render_1.setFrameShape(QFrame.HLine)
        self.line_render_1.setFrameShadow(QFrame.Sunken)
        self.layoutWidget_2 = QWidget(self.tab_2_render)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 230, 441, 121))
        self.gridLayout_7 = QGridLayout(self.layoutWidget_2)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_post_comment = QLabel(self.layoutWidget_2)
        self.label_post_comment.setObjectName(u"label_post_comment")
        self.label_post_comment.setMinimumSize(QSize(0, 20))
        self.label_post_comment.setMaximumSize(QSize(16777215, 20))
        self.label_post_comment.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)

        self.gridLayout_7.addWidget(self.label_post_comment, 0, 0, 1, 1)

        self.textEdit_leave_a_comment = QTextEdit(self.layoutWidget_2)
        self.textEdit_leave_a_comment.setObjectName(u"textEdit_leave_a_comment")
        sizePolicy.setHeightForWidth(self.textEdit_leave_a_comment.sizePolicy().hasHeightForWidth())
        self.textEdit_leave_a_comment.setSizePolicy(sizePolicy)
        self.textEdit_leave_a_comment.setMinimumSize(QSize(0, 70))
        self.textEdit_leave_a_comment.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout_7.addWidget(self.textEdit_leave_a_comment, 1, 0, 1, 1)

        self.pushButton_publish = QPushButton(self.layoutWidget_2)
        self.pushButton_publish.setObjectName(u"pushButton_publish")
        sizePolicy1.setHeightForWidth(self.pushButton_publish.sizePolicy().hasHeightForWidth())
        self.pushButton_publish.setSizePolicy(sizePolicy1)
        self.pushButton_publish.setMinimumSize(QSize(90, 70))
        self.pushButton_publish.setMaximumSize(QSize(16777215, 16777215))

        self.gridLayout_7.addWidget(self.pushButton_publish, 1, 1, 1, 1)

        self.commandLinkButton_go_kitsu_2 = QCommandLinkButton(self.tab_2_render)
        self.commandLinkButton_go_kitsu_2.setObjectName(u"commandLinkButton_go_kitsu_2")
        self.commandLinkButton_go_kitsu_2.setGeometry(QRect(359, 360, 90, 34))
        self.commandLinkButton_go_kitsu_2.setMinimumSize(QSize(0, 0))
        self.commandLinkButton_go_kitsu_2.setMaximumSize(QSize(100, 100))
        self.commandLinkButton_go_kitsu_2.setSizeIncrement(QSize(0, 0))
        self.commandLinkButton_go_kitsu_2.setFont(font)
        self.commandLinkButton_go_kitsu_2.setFocusPolicy(Qt.WheelFocus)
        self.commandLinkButton_go_kitsu_2.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget.addTab(self.tab_2_render, "")
        MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.tabWidget, self.commandLinkButton_go_kitsu)
        QWidget.setTabOrder(self.commandLinkButton_go_kitsu, self.pushButton_logout)
        QWidget.setTabOrder(self.pushButton_logout, self.listWidget_vid_project)
        QWidget.setTabOrder(self.listWidget_vid_project, self.listWidget_vid_asset)
        QWidget.setTabOrder(self.listWidget_vid_asset, self.listWidget_change_hdri_img)
        QWidget.setTabOrder(self.listWidget_change_hdri_img, self.lineEdit_hdri_path)
        QWidget.setTabOrder(self.lineEdit_hdri_path, self.pushButton_hdri_path)
        QWidget.setTabOrder(self.pushButton_hdri_path, self.pushButton_publish_hdri_img)
        QWidget.setTabOrder(self.pushButton_publish_hdri_img, self.checkBox_change_setting)
        QWidget.setTabOrder(self.checkBox_change_setting, self.lineEdit_mesh_start_frame)
        QWidget.setTabOrder(self.lineEdit_mesh_start_frame, self.lineEdit_mesh_end_frame)
        QWidget.setTabOrder(self.lineEdit_mesh_end_frame, self.lineEdit_img_name)
        QWidget.setTabOrder(self.lineEdit_img_name, self.lineEdit_img_format)
        QWidget.setTabOrder(self.lineEdit_img_format, self.lineEdit_img_path)
        QWidget.setTabOrder(self.lineEdit_img_path, self.lineEdit_vid_name)
        QWidget.setTabOrder(self.lineEdit_vid_name, self.lineEdit_vid_format)
        QWidget.setTabOrder(self.lineEdit_vid_format, self.lineEdit_vid_path)
        QWidget.setTabOrder(self.lineEdit_vid_path, self.lineEdit_aa_sam)
        QWidget.setTabOrder(self.lineEdit_aa_sam, self.lineEdit_diffuse_sam)
        QWidget.setTabOrder(self.lineEdit_diffuse_sam, self.lineEdit_specular_sam)
        QWidget.setTabOrder(self.lineEdit_specular_sam, self.lineEdit_trans_sam)
        QWidget.setTabOrder(self.lineEdit_trans_sam, self.lineEdit_sss_sam)
        QWidget.setTabOrder(self.lineEdit_sss_sam, self.lineEdit_volume_sam)
        QWidget.setTabOrder(self.lineEdit_volume_sam, self.listWidget_availaov)
        QWidget.setTabOrder(self.listWidget_availaov, self.listWidget_activaov)
        QWidget.setTabOrder(self.listWidget_activaov, self.pushButton_import)
        QWidget.setTabOrder(self.pushButton_import, self.lineEdit_scene_name)
        QWidget.setTabOrder(self.lineEdit_scene_name, self.comboBox_scene_format)
        QWidget.setTabOrder(self.comboBox_scene_format, self.lineEdit_scene_path)
        QWidget.setTabOrder(self.lineEdit_scene_path, self.pushButton_scene_path)
        QWidget.setTabOrder(self.pushButton_scene_path, self.pushButton_save_scene)
        QWidget.setTabOrder(self.pushButton_save_scene, self.textEdit_leave_a_comment)
        QWidget.setTabOrder(self.textEdit_leave_a_comment, self.pushButton_publish)
        QWidget.setTabOrder(self.pushButton_publish, self.commandLinkButton_go_kitsu_2)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"EZ PUB", None))
        self.kitsuLayout_2.setTitle("")
        self.label_user_name.setText(QCoreApplication.translate("MainWindow", u"'user_name'", None))
        self.pushButton_logout.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.commandLinkButton_go_kitsu.setText(QCoreApplication.translate("MainWindow", u"Go Kitsu", None))
        self.label_vid_project.setText(QCoreApplication.translate("MainWindow", u"Project:", None))
        self.label_vid_asset.setText(QCoreApplication.translate("MainWindow", u"Asset:", None))
        self.hdriLayout_2.setTitle("")
        self.label_preview_hdri_img_import.setText(QCoreApplication.translate("MainWindow", u"Preview the HDRI image to be imported...", None))
        self.label_change_hdri_img.setText(QCoreApplication.translate("MainWindow", u"[ Change HDRI Image ]", None))
        self.hdriLayout_1.setTitle("")
        self.label_preview_hdri_img_add.setText(QCoreApplication.translate("MainWindow", u"Preview the HDRI image to be added...", None))
        self.label_hdri_path_2.setText(QCoreApplication.translate("MainWindow", u"File path: ", None))
        self.lineEdit_hdri_path.setText("")
        self.lineEdit_hdri_path.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ex. /directory", None))
        self.pushButton_hdri_path.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.label_publish_hdri_img.setText(QCoreApplication.translate("MainWindow", u"[ Publish HDRI Image ]", None))
        self.pushButton_publish_hdri_img.setText(QCoreApplication.translate("MainWindow", u"Publish HDRI Image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3_kitsu), QCoreApplication.translate("MainWindow", u"Kitsu and HDRI", None))
        self.pushButton_import.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.lineEdit_sss_sam.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.lineEdit_sss_sam.setPlaceholderText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_aov_setting.setText(QCoreApplication.translate("MainWindow", u"[ AOV Setting ]", None))
        self.label_diffuse_sam.setText(QCoreApplication.translate("MainWindow", u"Diffuse", None))
        self.label_availaov.setText(QCoreApplication.translate("MainWindow", u": Available AOV", None))
        self.label_sample_setting.setText(QCoreApplication.translate("MainWindow", u"[ Sample Setting ]", None))
        self.lineEdit_specular_sam.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.lineEdit_specular_sam.setPlaceholderText(QCoreApplication.translate("MainWindow", u"4", None))
        self.lineEdit_trans_sam.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.lineEdit_trans_sam.setPlaceholderText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_sss_sam.setText(QCoreApplication.translate("MainWindow", u"SSS", None))
        self.lineEdit_diffuse_sam.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.lineEdit_diffuse_sam.setPlaceholderText(QCoreApplication.translate("MainWindow", u"6", None))
        self.label_activaov.setText(QCoreApplication.translate("MainWindow", u": Active AOV", None))
        self.lineEdit_aa_sam.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.lineEdit_aa_sam.setPlaceholderText(QCoreApplication.translate("MainWindow", u"8", None))

        __sortingEnabled = self.listWidget_availaov.isSortingEnabled()
        self.listWidget_availaov.setSortingEnabled(False)
        ___qlistwidgetitem = self.listWidget_availaov.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"albedo", None));
        ___qlistwidgetitem1 = self.listWidget_availaov.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"background", None));
        ___qlistwidgetitem2 = self.listWidget_availaov.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("MainWindow", u"coat", None));
        ___qlistwidgetitem3 = self.listWidget_availaov.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("MainWindow", u"diffuse", None));
        ___qlistwidgetitem4 = self.listWidget_availaov.item(4)
        ___qlistwidgetitem4.setText(QCoreApplication.translate("MainWindow", u"direct", None));
        ___qlistwidgetitem5 = self.listWidget_availaov.item(5)
        ___qlistwidgetitem5.setText(QCoreApplication.translate("MainWindow", u"emission", None));
        ___qlistwidgetitem6 = self.listWidget_availaov.item(6)
        ___qlistwidgetitem6.setText(QCoreApplication.translate("MainWindow", u"indirect", None));
        ___qlistwidgetitem7 = self.listWidget_availaov.item(7)
        ___qlistwidgetitem7.setText(QCoreApplication.translate("MainWindow", u"opacity", None));
        ___qlistwidgetitem8 = self.listWidget_availaov.item(8)
        ___qlistwidgetitem8.setText(QCoreApplication.translate("MainWindow", u"RGBA", None));
        ___qlistwidgetitem9 = self.listWidget_availaov.item(9)
        ___qlistwidgetitem9.setText(QCoreApplication.translate("MainWindow", u"sheen", None));
        ___qlistwidgetitem10 = self.listWidget_availaov.item(10)
        ___qlistwidgetitem10.setText(QCoreApplication.translate("MainWindow", u"specular", None));
        ___qlistwidgetitem11 = self.listWidget_availaov.item(11)
        ___qlistwidgetitem11.setText(QCoreApplication.translate("MainWindow", u"transmission", None));
        ___qlistwidgetitem12 = self.listWidget_availaov.item(12)
        ___qlistwidgetitem12.setText(QCoreApplication.translate("MainWindow", u"volume", None));
        self.listWidget_availaov.setSortingEnabled(__sortingEnabled)

        self.lineEdit_volume_sam.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.lineEdit_volume_sam.setPlaceholderText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_aa_sam.setText(QCoreApplication.translate("MainWindow", u"Camera(AA)", None))
        self.label_specular_sam.setText(QCoreApplication.translate("MainWindow", u"Specular", None))
        self.label_volume_sam.setText(QCoreApplication.translate("MainWindow", u"Volume Indirect", None))
        self.label_trans_sam.setText(QCoreApplication.translate("MainWindow", u"Transmission", None))
        self.label_vid_name.setText(QCoreApplication.translate("MainWindow", u"Video Name:", None))
        self.label_img_format.setText(QCoreApplication.translate("MainWindow", u"Image Format:", None))
        self.label_mesh_start_frame.setText(QCoreApplication.translate("MainWindow", u"Start Frame:", None))
        self.label_vid_path.setText(QCoreApplication.translate("MainWindow", u"Video Path: ", None))
        self.label_mesh_end_frame.setText(QCoreApplication.translate("MainWindow", u"End Frame:", None))
        self.checkBox_change_setting.setText(QCoreApplication.translate("MainWindow", u"Enable Setting", None))
        self.label_img_path.setText(QCoreApplication.translate("MainWindow", u"Image Path: ", None))
        self.lineEdit_mesh_start_frame.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.lineEdit_mesh_start_frame.setPlaceholderText(QCoreApplication.translate("MainWindow", u"1", None))
        self.lineEdit_mesh_end_frame.setText(QCoreApplication.translate("MainWindow", u"24", None))
        self.lineEdit_mesh_end_frame.setPlaceholderText(QCoreApplication.translate("MainWindow", u"24", None))
        self.lineEdit_vid_format.setText(QCoreApplication.translate("MainWindow", u"mov", None))
        self.lineEdit_vid_format.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ex. mov", None))
        self.label_video_setting.setText(QCoreApplication.translate("MainWindow", u"[ Video Setting ]", None))
        self.label_vid_format.setText(QCoreApplication.translate("MainWindow", u"Video Format:", None))
        self.lineEdit_vid_path.setText("")
        self.lineEdit_vid_path.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ex. /directory", None))
        self.label_img_name.setText(QCoreApplication.translate("MainWindow", u"Image Name:", None))
        self.lineEdit_vid_name.setText("")
        self.lineEdit_vid_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ex. video_name", None))
        self.lineEdit_img_path.setText("")
        self.lineEdit_img_path.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ex. /directory", None))
        self.lineEdit_img_format.setText(QCoreApplication.translate("MainWindow", u"exr", None))
        self.lineEdit_img_format.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ex. exr", None))
        self.lineEdit_img_name.setText("")
        self.lineEdit_img_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ex. image_name", None))
        self.label_mesh.setText(QCoreApplication.translate("MainWindow", u"[ Render Range ]", None))
        self.renderLayout_1.setTitle("")
        self.label_name.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.label_selected_mesh_name.setText(QCoreApplication.translate("MainWindow", u"'selected_mesh_name'", None))
        self.label_camera.setText(QCoreApplication.translate("MainWindow", u"Camera:", None))
        self.label_selected_camera_name.setText(QCoreApplication.translate("MainWindow", u"'selected_camera_name'", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1_hdri), QCoreApplication.translate("MainWindow", u"Setting and Import", None))
        self.renderLayout_3.setTitle("")
        self.label_scene_name.setText(QCoreApplication.translate("MainWindow", u"Scene Name:", None))
        self.lineEdit_scene_name.setText("")
        self.lineEdit_scene_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ex. scene_file_name", None))
        self.comboBox_scene_format.setItemText(0, QCoreApplication.translate("MainWindow", u".ma", None))
        self.comboBox_scene_format.setItemText(1, QCoreApplication.translate("MainWindow", u".mb", None))

        self.label_scene_path.setText(QCoreApplication.translate("MainWindow", u"Scene Path: ", None))
        self.lineEdit_scene_path.setText("")
        self.lineEdit_scene_path.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ex. /directory", None))
        self.pushButton_scene_path.setText(QCoreApplication.translate("MainWindow", u"<<<", None))
        self.label_save_scene_file.setText(QCoreApplication.translate("MainWindow", u"[ Save Scene File ]", None))
        self.pushButton_save_scene.setText(QCoreApplication.translate("MainWindow", u"Save Scene", None))
        self.label_post_comment.setText(QCoreApplication.translate("MainWindow", u"Post Comment:", None))
        self.textEdit_leave_a_comment.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Cantarell'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.textEdit_leave_a_comment.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Leave a comment...", None))
        self.pushButton_publish.setText(QCoreApplication.translate("MainWindow", u"Publish", None))
        self.commandLinkButton_go_kitsu_2.setText(QCoreApplication.translate("MainWindow", u"Go Kitsu", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2_render), QCoreApplication.translate("MainWindow", u"Save and Publish", None))
    # retranslateUi

